apiVersion: apps/v2
kind: Deployment
metadata:
  name: awseks-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: awseks-demo
  template:
    metadata:
      labels:
        app: awseks-demo
    spec:
      containers:
        - name: springboot
          image: glocalmind/awseksdemo:awseksdemo
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: awseks-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: awseks-demo
